2018-12-09 13:55:54 INFO db_query [db.py-44] select * from user where name='张三'
2018-12-09 13:55:54 INFO <module> [run.py-9] 测试开始==================================================
2018-12-09 13:55:54 INFO _new_conn [connectionpool.py-214] Starting new HTTP connection (1): 115.28.108.130
2018-12-09 13:55:54 DEBUG _make_request [connectionpool.py-401] "POST /api/user/login/ HTTP/1.1" 200 21
2018-12-09 13:55:54 INFO log_case_info [case_log.py-3] ----------------------------------------------------------------------------------------------------
2018-12-09 13:55:54 INFO log_case_info [case_log.py-4] 执行用例：test_user_login_normal
2018-12-09 13:55:54 INFO log_case_info [case_log.py-5] 接口地址：http://115.28.108.130:5000/api/user/login/
2018-12-09 13:55:54 INFO log_case_info [case_log.py-6] 请求数据:<h1>登录成功</h1>
2018-12-09 13:55:54 INFO log_case_info [case_log.py-7] 期望结果:<h1>登录成功</h1>
2018-12-09 13:55:54 INFO _new_conn [connectionpool.py-214] Starting new HTTP connection (1): 115.28.108.130
2018-12-09 13:55:54 DEBUG _make_request [connectionpool.py-401] "POST /api/user/login/ HTTP/1.1" 200 42
2018-12-09 13:55:54 INFO log_case_info [case_log.py-3] ----------------------------------------------------------------------------------------------------
2018-12-09 13:55:54 INFO log_case_info [case_log.py-4] 执行用例：test_user_login_password_wrong
2018-12-09 13:55:54 INFO log_case_info [case_log.py-5] 接口地址：http://115.28.108.130:5000/api/user/login/
2018-12-09 13:55:54 INFO log_case_info [case_log.py-6] 请求数据:<h1>失败，用户名或密码错误</h1>
2018-12-09 13:55:54 INFO log_case_info [case_log.py-7] 期望结果:<h1>失败，用户名或密码错误</h1>
2018-12-09 13:55:54 INFO db_query [db.py-44] select * from user where name='张三丰'
2018-12-09 13:55:54 INFO _new_conn [connectionpool.py-214] Starting new HTTP connection (1): 115.28.108.130
2018-12-09 13:55:54 DEBUG _make_request [connectionpool.py-401] "POST /api/user/reg/ HTTP/1.1" 200 122
2018-12-09 13:55:55 INFO log_case_info [case_log.py-3] ----------------------------------------------------------------------------------------------------
2018-12-09 13:55:55 INFO log_case_info [case_log.py-4] 执行用例：test_user_reg_normal
2018-12-09 13:55:55 INFO log_case_info [case_log.py-5] 接口地址：http://115.28.108.130:5000/api/user/reg/
2018-12-09 13:55:55 INFO log_case_info [case_log.py-6] 请求数据:{
    "code": "100000",
    "data": {
        "name": "张三丰",
        "password": "e10adc3949ba59abbe56e057f20f883e"
    },
    "msg": "成功"
}
2018-12-09 13:55:55 INFO log_case_info [case_log.py-7] 期望结果:{"code":"100000","data":{"name":"\u5f20\u4e09\u4e30","password":"e10adc3949ba59abbe56e057f20f883e"},"msg":"\u6210\u529f"}

2018-12-09 13:55:55 INFO db_change [db.py-55] delete from user where name='张三丰'
2018-12-09 13:55:55 INFO _new_conn [connectionpool.py-214] Starting new HTTP connection (1): 115.28.108.130
2018-12-09 13:55:55 DEBUG _make_request [connectionpool.py-401] "POST /api/user/reg/ HTTP/1.1" 200 152
2018-12-09 13:56:04 INFO <module> [run.py-14] 发送邮件成功
2018-12-09 13:56:04 INFO <module> [run.py-15] 测试结束==================================================
